apiVersion: v2
name: m365-exporter
description: A Helm chart for m365-exporter
type: application
version: 1.1.0
# renovate: docker=ghcr.io/cloudeteer/m365-exporter
appVersion: 3.3.0
home: https://github.com/cloudeteer/m365-exporter
sources:
  - https://github.com/cloudeteer/helm-charts/tree/main/charts/m365-exporter
  - https://github.com/cloudeteer/m365-exporter
maintainers:
  - name: cloudeteer
    email: engineering@cloudeteer.de
    url: https://cloudeteer.de
keywords:
  - prometheus
  - exporter
  - m365
  - microsoft
icon: https://raw.githubusercontent.com/cloudeteer/m365-exporter/refs/heads/main/docs/sources/assets/logo_m365_exporter.svg
